#!/usr/bin/env bash
# This script changes localhost and facebook.com IPs

# Remove existing entries if they exist
sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# Add new IPs
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
